### ISSUE TITLE
How to get the file URL?

### ISSUE THREAD

**Issue by richcorbs** [sampoder/berowra#10]
The documentation on how to get a file URL is not clear. It says:

```
For any files returned by the API, prepend /file/ and the host URL to get a web URL.
```

Maybe an example URL could be added to the documentation?

I've tried prepending `/file/` in lots of places in the path and have not gotten anywhere.

**Comment by sampoder** [comment]
The API will return something like:

```
{"title":null,"type":"Files","value":["2021-11-3008:29:07.707108+00:00d7hftxdivxxvm.cloudfront.net"]}
```

If you prepend `/file/` to the value to create `/file/2021-11-3008:29:07.707108+00:00d7hftxdivxxvm.cloudfront.net` it should then work
