### ISSUE TITLE
Add code blocks to markdown editor

### ISSUE THREAD

**Issue by salemalem** [sampoder/berowra#6]
When I write `` to wrap my code the text resets.

**Comment by sampoder** [comment]
Thanks for reporting! On my list to fix tonight.

**Comment by sampoder** [comment]
Fixed in 2e21652 :D Will go live on Deta Space soon

**Comment by salemalem** [comment]
Let me close this issue once I will test your new update.

**Comment by sampoder** [comment]
The fix is live!

**Comment by salemalem** [comment]
Thank you, I am out from my laptop. Will come back in 24/48 hours.

**Comment by sampoder** [comment]
Closing for now, have tested myself please open a new issue if any issue arise. Thanks for the help.

**Comment by salemalem** [comment]
Sure, dude!
