### ISSUE TITLE
Is it possible to edit existing collection?

### ISSUE THREAD

**Issue by freeman14** [sampoder/berowra#7]

**Comment by sampoder** [comment]
Sorry not at the moment but this is the next feature to be implemented

**Comment by freeman14** [comment]
Looking forward to seeing that. 
Btw do you have a road map?

**Comment by sampoder** [comment]
Nothing at the moment, but it's something I'll look into

**Comment by sampoder** [comment]
Been implemented in 7276126, will test further and then publish in Deta Space

<img width="1551" alt="Screenshot 2021-08-15 at 12 13 34 AM" src="https://user-images.githubusercontent.com/39828164/129452594-472cd8c4-ff53-4ed3-a0b4-4dfbfc64dcdf.png">

**Comment by sampoder** [comment]
This feature is now live on Deta Space :D
